[sd]
Reliable = "/run/shm/sciond/sd1-ff00_0_112.sock"
Unix = "/run/shm/sciond/sd1-ff00_0_112.unix"
Public = "1-ff00:0:112,[127.0.0.1]:0"

[general]
ReconnectToDispatcher = true
ID = "sd1-ff00_0_112"
ConfigDir = "gen/ISD1/ASff00_0_112/endhost"

[TrustDB]
Backend = "sqlite"
Connection = "gen-cache/sd1-ff00_0_112.trust.db"

[logging.file]
Level = "debug"
Path = "logs/sd1-ff00_0_112.log"

[logging.console]
Level = "crit"

[sd.PathDB]
Connection = "gen-cache/sd1-ff00_0_112.path.db"
